name: rclone-from-github
license: MIT
adopt-info: rclone  # for "snapcraftctl set-version" below
summary: rclone syncs files and directories between different cloud storage providers
description: |
    Rclone is a command line program to manage files on cloud storage. It is a feature rich alternative to cloud vendors' web storage interfaces. Over 40 cloud storage products support rclone including S3 object stores, business & consumer file storage services, as well as standard transfer protocols.

    Rclone has powerful cloud equivalents to the unix commands rsync, cp, mv, mount, ls, ncdu, tree, rm, and cat. Rclone's familiar syntax includes shell pipeline support, and --dry-run protection. It is used at the command line, in scripts or via its API.

    Users call rclone "The Swiss army knife of cloud storage", and "Technology indistinguishable from magic".

    Rclone really looks after your data. It preserves timestamps and verifies checksums at all times. Transfers over limited bandwidth; intermittent connections, or subject to quota can be restarted, from the last good file transferred. You can check the integrity of your files. Where possible, rclone employs server-side transfers to minimise local bandwidth use and transfers from one provider to another without using local disk.

    Virtual backends wrap local and cloud file systems to apply encryption, compression, chunking, hashing and joining.

    Rclone mounts any local, cloud or virtual filesystem as a disk on Windows, macOS, linux and FreeBSD, and also serves these over SFTP, HTTP, WebDAV, FTP and DLNA.

    Rclone is mature, open source software originally inspired by rsync and written in Go. The friendly support community are familiar with varied use cases. Official Ubuntu, Debian, Fedora, Brew and Chocolatey repos. include rclone. For the latest version downloading from rclone.org is recommended.

    Rclone is widely used on Linux, Windows and Mac. Third party developers create innovative backup, restore, GUI and business process solutions using the rclone command line or API.

    Rclone does the heavy lifting of communicating with cloud storage.

    For help with this snap, please create a topic on https://forum.snapcraft.io/ unless you can reproduce the problem with one of the official releases from https://rclone.org/downloads/.

    To use this snap as a drop-in replacement for rclone, run "snap alias rclone-from-github rclone".
base: core20

confinement: strict
grade: stable

plugs:
    home:
    network:

apps:
    rclone-from-github:
        command: bin/rclone
        adapter: none
parts:
    rclone:
        plugin: go
        source: https://github.com/rclone/rclone.git
        build-environment:
            # https://github.com/golang/go/issues/33840
            - CGO_ENABLED: "0"
        build-snaps:
            - go
        override-pull: |
          snapcraftctl pull
          snapcraftctl set-version $(git describe)
